/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Customer;
import Model.DelPackage;
import Model.Product;

import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author divya
 */
public class EditJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditJPanel
     */
    private DelPackage delpackage;
    
    private Product productViewed;
    
    
    
    public EditJPanel() {
        initComponents();
        
      
    }


   public  EditJPanel(DelPackage deliverypackage) {
        initComponents();
        
      this.delpackage = deliverypackage;
      
      
        displayProductList();
        
        displayPackageDetails();


//  throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Updatebtn = new javax.swing.JButton();
        fpackId = new javax.swing.JTextField();
        fpackWt = new javax.swing.JTextField();
        fprodName = new javax.swing.JTextField();
        fprodId = new javax.swing.JTextField();
        fprodPrice = new javax.swing.JTextField();
        fcustName = new javax.swing.JTextField();
        prodComboBox = new javax.swing.JComboBox();
        showBtn = new javax.swing.JButton();
        updateProdbtn = new javax.swing.JButton();
        fcustID = new javax.swing.JTextField();

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("package Id");

        jLabel2.setText("package wt");

        jLabel3.setText("prod name");

        jLabel4.setText("prod id");

        jLabel5.setText("prod price");

        jLabel6.setText("cust id");

        jLabel7.setText("cust name");

        Updatebtn.setText("Update");
        Updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnActionPerformed(evt);
            }
        });

        fprodId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fprodIdActionPerformed(evt);
            }
        });

        prodComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodComboBoxActionPerformed(evt);
            }
        });

        showBtn.setText("Show");
        showBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBtnActionPerformed(evt);
            }
        });

        updateProdbtn.setText("Update Product");
        updateProdbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProdbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(prodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(showBtn)
                                .addGap(56, 56, 56))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(fpackWt))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(fpackId, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(fcustName, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(fcustID)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fprodId, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fprodName)
                                    .addComponent(fprodPrice))
                                .addGap(139, 139, 139)))
                        .addComponent(Updatebtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(updateProdbtn)))
                .addGap(115, 115, 115))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(fpackId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fcustID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(fpackWt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fcustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Updatebtn))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showBtn))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fprodId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fprodName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fprodPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(33, 33, 33)
                .addComponent(updateProdbtn)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnActionPerformed
        // TODO add your handling code here:

       
        String packageID = fpackId.getText();
        String packageWt = fpackWt.getText();
        
        String CustID = fcustID.getText();
        String custName = fcustName.getText();
        
        
       this.delpackage.setPackageID(Integer.valueOf(packageID));
        this.delpackage.setPackageWeight(Double.valueOf(packageWt));
        
        Customer customer = this.delpackage.getCustomer();
        customer.setCustID(Integer.valueOf(CustID));
        customer.setcustName(custName);
       
             
        
        
       

    }//GEN-LAST:event_UpdatebtnActionPerformed

    private void prodComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodComboBoxActionPerformed
        // TODO add your handling code here:
        
       //for(Product p: this.delpackage.getProductList())
               // {
                //    productComboBox.addItem(p.getProdId());
               // }
    }//GEN-LAST:event_prodComboBoxActionPerformed

    private void showBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBtnActionPerformed
        // TODO add your handling code here:

     fprodId.setEnabled(false);
        
        int pid = (int) prodComboBox.getSelectedItem();

        // find the product in the arraylsit
         Product prod = this.delpackage.findProduct(pid);
         this.productViewed = prod;
        // display the product content

        if (!prod.equals(null)) 
{
            fprodId.setText(String.valueOf(pid));
            fprodName.setText(prod.getProdName());
            fprodPrice.setText(String.valueOf(prod.getProdPrice()));
        } 
else {
            JOptionPane.showMessageDialog(null, "Product not found");
        }
    }//GEN-LAST:event_showBtnActionPerformed

    private void updateProdbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProdbtnActionPerformed
        // TODO add your handling code here:


          
          this.productViewed.setProdName(fprodName.getText());
          this.productViewed.setProdPrice(Double.valueOf(fprodPrice.getText()));





    }//GEN-LAST:event_updateProdbtnActionPerformed

    private void fprodIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fprodIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fprodIdActionPerformed
    
    
    
    
    
    
    
    
    public void displayProductList() {
        

        for (Product p : this.delpackage.getProductList()) {
            prodComboBox.addItem(p.getProdId());
        }

    }
      public void displayPackageDetails() {
        fpackId.setText(String.valueOf(this.delpackage.getPackageID()));
        fpackWt.setText(String.valueOf(this.delpackage.getPackageWeight()));

        Customer customer = this.delpackage.getCustomer();
        fcustID.setText(String.valueOf(customer.getCustID()));
        fcustName.setText(customer.getcustName());

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Updatebtn;
    private javax.swing.JTextField fcustID;
    private javax.swing.JTextField fcustName;
    private javax.swing.JTextField fpackId;
    private javax.swing.JTextField fpackWt;
    private javax.swing.JTextField fprodId;
    private javax.swing.JTextField fprodName;
    private javax.swing.JTextField fprodPrice;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox prodComboBox;
    private javax.swing.JButton showBtn;
    private javax.swing.JButton updateProdbtn;
    // End of variables declaration//GEN-END:variables
}
