/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Application;
import javax.swing.JSplitPane;

/**
 *
 * @author divya
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    Application application;
    
    public MainJFrame() {
        initComponents();
        this.application= new Application();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        ControlPanel = new javax.swing.JPanel();
        CreateObBtn = new javax.swing.JButton();
        vitalSignHistoryBtn = new javax.swing.JButton();
        MedicineCatalougeBtn = new javax.swing.JButton();
        AssignBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ControlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CreateObBtn.setText("Create Observation");
        CreateObBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateObBtnActionPerformed(evt);
            }
        });
        ControlPanel.add(CreateObBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 49, -1, -1));

        vitalSignHistoryBtn.setText("Vital Sign History");
        vitalSignHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vitalSignHistoryBtnActionPerformed(evt);
            }
        });
        ControlPanel.add(vitalSignHistoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 114, -1, -1));

        MedicineCatalougeBtn.setText("Medicine Catalouge");
        MedicineCatalougeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicineCatalougeBtnActionPerformed(evt);
            }
        });
        ControlPanel.add(MedicineCatalougeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 171, -1, -1));

        AssignBtn.setText("Assign");
        AssignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignBtnActionPerformed(evt);
            }
        });
        ControlPanel.add(AssignBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jSplitPane1.setLeftComponent(ControlPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateObBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateObBtnActionPerformed
        // TODO add your handling code here:
        
        
        jSplitPane1.setRightComponent(new CreateJPanel(this.application));
        
    }//GEN-LAST:event_CreateObBtnActionPerformed

    private void vitalSignHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitalSignHistoryBtnActionPerformed
        // TODO add your handling code here:
        
           jSplitPane1.setRightComponent(new ViewJPanel(this.application));
    }//GEN-LAST:event_vitalSignHistoryBtnActionPerformed

    private void MedicineCatalougeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicineCatalougeBtnActionPerformed
        // TODO add your handling code here:
        
         jSplitPane1.setRightComponent(new CatalougePanel(this.application));
    }//GEN-LAST:event_MedicineCatalougeBtnActionPerformed

    private void AssignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignBtnActionPerformed
        // TODO add your handling code here:
        
         jSplitPane1.setRightComponent(new AssignPanel(this.application));
    }//GEN-LAST:event_AssignBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignBtn;
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JButton CreateObBtn;
    private javax.swing.JButton MedicineCatalougeBtn;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton vitalSignHistoryBtn;
    // End of variables declaration//GEN-END:variables
}
