/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Address;
import Model.Contact;
import Model.Person;

/**
 *
 * @author divya
 */
public class MainJframe extends javax.swing.JFrame {

    /**
     * Creates new form MainJframe
     */
     private Person person;
    
    public MainJframe() {
        initComponents();
        this.person=new Person();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField13 = new javax.swing.JTextField();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        feildFname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        feildLname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        feildNUID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fColName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fPhno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fCStreetName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        fCAptName = new javax.swing.JTextField();
        fCCity = new javax.swing.JTextField();
        fCState = new javax.swing.JTextField();
        fCZipcode = new javax.swing.JTextField();
        fPStreetName = new javax.swing.JTextField();
        fPAptno = new javax.swing.JTextField();
        fPCity = new javax.swing.JTextField();
        fPState = new javax.swing.JTextField();
        fpZipcode = new javax.swing.JTextField();
        Savebtn = new javax.swing.JButton();
        ViewJpanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        VFname = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        VLname = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        VNUID = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        VColName = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        VPhno = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        VEmail = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        VCStreetname = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        VCAptno = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        VCCity = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        VCState = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        VCZipcode = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        VPstreet = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        VPAptno = new javax.swing.JLabel();
        VPCity = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        VPState = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        VPZipcode = new javax.swing.JLabel();

        jTextField13.setText("jTextField13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("First Name");

        feildFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feildFnameActionPerformed(evt);
            }
        });

        jLabel2.setText("Last Name");

        jLabel3.setText("NUID");

        jLabel4.setText("College Name");

        jLabel5.setText("Phone No.");

        fPhno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fPhnoActionPerformed(evt);
            }
        });

        jLabel6.setText("Email ID");

        jLabel7.setText("Current Address");

        fCStreetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fCStreetNameActionPerformed(evt);
            }
        });

        jLabel9.setText("Street Name");

        jLabel11.setText("Apt Number");

        jLabel12.setText("City");

        jLabel13.setText("State");

        jLabel14.setText("Zipcode");

        jLabel15.setText("Present Address");

        jLabel16.setText("Street Name");

        jLabel17.setText("Apt Number");

        jLabel18.setText("City");

        jLabel19.setText("State");

        jLabel20.setText("Zipcode");

        Savebtn.setText("Submit");
        Savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(165, 165, 165))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)))
                                .addComponent(jLabel9)
                                .addComponent(jLabel14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(15, 15, 15)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fColName, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(feildLname)
                                    .addComponent(feildFname)
                                    .addComponent(feildNUID)
                                    .addComponent(fPhno)
                                    .addComponent(fEmail)
                                    .addComponent(fCState)
                                    .addComponent(fCZipcode)))
                            .addComponent(fCStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fCAptName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fCCity, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fPStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fPAptno, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fPCity, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fPState, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(94, 94, 94)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel20)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fpZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(Savebtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(feildFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(feildLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(feildNUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fColName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fPhno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(fEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fCStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(fPStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fCAptName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(fPAptno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fCCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(fPCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(fCState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(fPState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(fCZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(fpZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addGap(28, 28, 28)
                .addComponent(Savebtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(113, 113, 113))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jLabel21.setText("First Name");

        VFname.setText("jLabel22");

        jLabel23.setText("Last Name");

        VLname.setText("jLabel22");

        jLabel22.setText("NUID");

        VNUID.setText("jLabel24");

        jLabel24.setText("College Name");

        VColName.setText("jLabel25");

        jLabel25.setText("PhNo.");

        VPhno.setText("jLabel26");

        jLabel26.setText("Email ID");

        VEmail.setText("jLabel27");

        jLabel27.setText("Current Address");

        jLabel28.setText("Street Name");

        VCStreetname.setText("jLabel29");

        jLabel29.setText("AptNo.");

        VCAptno.setText("jLabel30");

        jLabel30.setText("City");

        VCCity.setText("jLabel31");

        jLabel31.setText("State");

        VCState.setText("jLabel32");

        jLabel32.setText("Zipcode");

        VCZipcode.setText("jLabel33");

        jLabel33.setText("Permenant Address");

        jLabel34.setText("Street Name");

        VPstreet.setText("jLabel35");

        jLabel35.setText("AptNo.");

        jLabel36.setText("City");

        VPAptno.setText("jLabel37");

        VPCity.setText("jLabel38");

        jLabel39.setText("State");

        VPState.setText("jLabel40");

        jLabel41.setText("Zipcode");

        VPZipcode.setText("jLabel42");

        javax.swing.GroupLayout ViewJpanelLayout = new javax.swing.GroupLayout(ViewJpanel);
        ViewJpanel.setLayout(ViewJpanelLayout);
        ViewJpanelLayout.setHorizontalGroup(
            ViewJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewJpanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(ViewJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ViewJpanelLayout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VCZipcode))
                    .addGroup(ViewJpanelLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VCState))
                    .addGroup(ViewJpanelLayout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VCCity))
                    .addGroup(ViewJpanelLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VCAptno))
                    .addGroup(ViewJpanelLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VCStreetname))
                    .addGroup(ViewJpanelLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VEmail))
                    .addGroup(ViewJpanelLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VPhno))
                    .addGroup(ViewJpanelLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VNUID))
                    .addGroup(ViewJpanelLayout.createSequentialGroup()
                        .addGroup(ViewJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23))
                        .addGap(121, 121, 121)
                        .addGroup(ViewJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(VFname)
                            .addComponent(VLname)))
                    .addGroup(ViewJpanelLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VColName)))
                .addGap(92, 92, 92)
                .addGroup(ViewJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ViewJpanelLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(74, 74, 74)
                        .addComponent(VPstreet))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ViewJpanelLayout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VPAptno))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ViewJpanelLayout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VPCity))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ViewJpanelLayout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VPState))
                    .addGroup(ViewJpanelLayout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VPZipcode)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ViewJpanelLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addGap(150, 150, 150))
        );
        ViewJpanelLayout.setVerticalGroup(
            ViewJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewJpanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(ViewJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(VFname))
                .addGap(18, 18, 18)
                .addGroup(ViewJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(VLname))
                .addGap(18, 18, 18)
                .addGroup(ViewJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(VNUID))
                .addGap(29, 29, 29)
                .addGroup(ViewJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(VColName))
                .addGap(30, 30, 30)
                .addGroup(ViewJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(VPhno))
                .addGap(18, 18, 18)
                .addGroup(ViewJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(VEmail))
                .addGap(31, 31, 31)
                .addGroup(ViewJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel33))
                .addGap(18, 18, 18)
                .addGroup(ViewJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(VCStreetname)
                    .addComponent(jLabel34)
                    .addComponent(VPstreet))
                .addGap(18, 18, 18)
                .addGroup(ViewJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(VCAptno)
                    .addComponent(jLabel35)
                    .addComponent(VPAptno))
                .addGap(28, 28, 28)
                .addGroup(ViewJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(VCCity)
                    .addComponent(jLabel36)
                    .addComponent(VPCity))
                .addGap(29, 29, 29)
                .addGroup(ViewJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(VCState)
                    .addComponent(jLabel39)
                    .addComponent(VPState))
                .addGap(29, 29, 29)
                .addGroup(ViewJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(VCZipcode)
                    .addComponent(jLabel41)
                    .addComponent(VPZipcode))
                .addContainerGap(288, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(ViewJpanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void feildFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feildFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feildFnameActionPerformed

    private void fPhnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fPhnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fPhnoActionPerformed

    private void fCStreetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fCStreetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fCStreetNameActionPerformed

    private void SavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavebtnActionPerformed
        // TODO add your handling code here:
        
        
        String fname = feildFname.getText();
        String  lname = feildLname.getText();
        long  NUID = Long.valueOf(feildNUID.getText());
       
        
        String  colName = fColName.getText();
        String  cstreet = fCStreetName.getText();
        
        long  fcaptno =Long.valueOf(fCAptName.getText());
        
        String  fccity = fCCity.getText();
        String  fcstate = fCState.getText();
        long fczipcode= Long.valueOf(fCZipcode.getText());
        
        
        
        String  fpstreet = fPStreetName.getText();
        long  fpaptno = Long.valueOf(fPAptno.getText());
        String  fpcity = fPCity.getText();
        String  fpstate = fPState.getText();
        long fpzipcode =Long.valueOf(fpZipcode.getText());
        
       long fphno = Long.valueOf(fPhno.getText());
        
       String femail= fEmail.getText();
       
       
        
        this.person.setFname(fname);
        this.person.setLname(lname);
        this.person.setNUID(NUID);
        this.person.setCollegename(colName);
        
       // Person obj2 = new Person();
        
        Address address = this.person.getAddress();
        address.setCstreet(cstreet);
        address.setcAptno(fcaptno);
        address.setcCity(fccity);
        address.setcState(fcstate);
        address.setcZipCode(fczipcode);
        
        
        address.setPstreet(fpstreet);
        address.setpAptno(fpaptno);
        address.setpCity(fpcity);
        address.setpState(fpstate);
        address.setpZipCode(fpzipcode);
        
        Contact contact =this.person.getContact();
        contact.setPhno(fphno);
        contact.setEmail(femail);
        
        
        display();
    }//GEN-LAST:event_SavebtnActionPerformed
 public void display()
  {
    VFname.setText(this.person.getFname());
    VLname.setText(this.person.getLname());
    VNUID.setText(String.valueOf(this.person.getNUID()));
    VColName.setText(this.person.getCollegename());
    
    
    VCStreetname.setText(this.person.getAddress().getCstreet());
    VCAptno.setText(String.valueOf(this.person.getAddress().getcAptno()));
    VCCity.setText(this.person.getAddress().getcCity());
    VCState.setText(this.person.getAddress().getcState());
    VCZipcode.setText(String.valueOf(this.person.getAddress().getcZipCode()));
    
    
    
    VPstreet.setText(this.person.getAddress().getPstreet());
    VPAptno.setText(String.valueOf(this.person.getAddress().getpAptno()));
    VPCity.setText(this.person.getAddress().getpCity());
    VPState.setText(this.person.getAddress().getpState());
    VPZipcode.setText(String.valueOf(this.person.getAddress().getpZipCode()));
    
  //iewPersonalPhone.setText(String.valueOf(this.person.getPersonalContact().getPhoneNumber()));
  
  
  
    VPhno.setText(String.valueOf(this.person.getContact().getPhno()));
    VEmail.setText(this.person.getContact().getEmail());
  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Savebtn;
    private javax.swing.JLabel VCAptno;
    private javax.swing.JLabel VCCity;
    private javax.swing.JLabel VCState;
    private javax.swing.JLabel VCStreetname;
    private javax.swing.JLabel VCZipcode;
    private javax.swing.JLabel VColName;
    private javax.swing.JLabel VEmail;
    private javax.swing.JLabel VFname;
    private javax.swing.JLabel VLname;
    private javax.swing.JLabel VNUID;
    private javax.swing.JLabel VPAptno;
    private javax.swing.JLabel VPCity;
    private javax.swing.JLabel VPState;
    private javax.swing.JLabel VPZipcode;
    private javax.swing.JLabel VPhno;
    private javax.swing.JLabel VPstreet;
    private javax.swing.JPanel ViewJpanel;
    private javax.swing.JTextField fCAptName;
    private javax.swing.JTextField fCCity;
    private javax.swing.JTextField fCState;
    private javax.swing.JTextField fCStreetName;
    private javax.swing.JTextField fCZipcode;
    private javax.swing.JTextField fColName;
    private javax.swing.JTextField fEmail;
    private javax.swing.JTextField fPAptno;
    private javax.swing.JTextField fPCity;
    private javax.swing.JTextField fPState;
    private javax.swing.JTextField fPStreetName;
    private javax.swing.JTextField fPhno;
    private javax.swing.JTextField feildFname;
    private javax.swing.JTextField feildLname;
    private javax.swing.JTextField feildNUID;
    private javax.swing.JTextField fpZipcode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField13;
    // End of variables declaration//GEN-END:variables
}
